[package]
name = "cli-excel-rs"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
excel-rs-xlsx = { workspace = true }
excel-rs-csv = { workspace = true }
clap = "4.5.17"
